default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: <%= ENV["LOCAL_APP_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: encarta_recipe_app_development

test:
  <<: *default
  database: encarta_recipe_app_test

production:
  <<: *default
  database: encarta_recipe_app_production
  username: postgres
  password: <%= ENV["APP_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
